// src/data.js

const getRandomPrice = () => {
    // Generate a random price between 100 and 500
    return Math.floor(Math.random() * (500 - 100 + 1)) + 100;
};

export const hotels = [
    {
        id: 1,
        name: 'Sunset Paradise Resort',
        location: 'Hawaii',
        rating: 4.8,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Family Suite'],
        amenities: ['Free WiFi', 'Ocean View', 'Spa'],
        image: 'https://media.istockphoto.com/id/1333257950/photo/digitally-rendered-image-of-a-five-star-hotel-interior.jpg?s=612x612&w=0&k=20&c=cAMaQYc-dDz8xveLeM_-xsGtn41-2BJKRA6GrDuy-HE=',
    },
    {
        id: 2,
        name: 'Mountain Lodge',
        location: 'Aspen, CO',
        rating: 4.9,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Luxury Suite'],
        amenities: ['Free WiFi', 'Ski Access', 'Fireplace'],
        image: 'https://media.istockphoto.com/id/92007666/photo/posh-hotel-front.jpg?s=612x612&w=0&k=20&c=oJ_9x6kG-WO-8t_BIRWE3D4GN6pXLulmf7Lztr4Y-y8=',
    },
    {
        id: 3,
        name: 'Urban Oasis Hotel',
        location: 'New York, NY',
        rating: 4.7,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Penthouse'],
        amenities: ['Free WiFi', 'Rooftop Bar', 'Fitness Center'],
        image: 'https://media.istockphoto.com/id/1418784247/photo/luxury-hotel-lobby.jpg?s=612x612&w=0&k=20&c=6acpCJL56bu5DMs8LwkdY246wlH2eRFci0MKVyycLJw=',
    },
    {
        id: 4,
        name: 'Tropical Haven Resort',
        location: 'Bora Bora',
        rating: 5.0,
        price: getRandomPrice(),
        rooms: ['Bungalow', 'Overwater Bungalow', 'Villa'],
        amenities: ['Private Beach', 'Water Sports', 'Dining on the Beach'],
        image: 'https://media.istockphoto.com/id/1333257950/photo/digitally-rendered-image-of-a-five-star-hotel-interior.jpg?s=612x612&w=0&k=20&c=cAMaQYc-dDz8xveLeM_-xsGtn41-2BJKRA6GrDuy-HE=',
    },
    {
        id: 5,
        name: 'Elegant Escape Inn',
        location: 'Paris, France',
        rating: 4.6,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Junior Suite'],
        amenities: ['Free WiFi', 'Breakfast Included', 'Eiffel Tower View'],
        image: 'https://media.istockphoto.com/id/92007666/photo/posh-hotel-front.jpg?s=612x612&w=0&k=20&c=oJ_9x6kG-WO-8t_BIRWE3D4GN6pXLulmf7Lztr4Y-y8=',
    },
    {
        id: 6,
        name: 'Desert Mirage Hotel',
        location: 'Palm Springs, CA',
        rating: 4.4,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Luxury Suite'],
        amenities: ['Free WiFi', 'Poolside Bar', 'Spa Services'],
        image: 'https://media.istockphoto.com/id/1418784247/photo/luxury-hotel-lobby.jpg?s=612x612&w=0&k=20&c=6acpCJL56bu5DMs8LwkdY246wlH2eRFci0MKVyycLJw=',
    },
    {
        id: 7,
        name: 'Seaside Retreat Hotel',
        location: 'Malibu, CA',
        rating: 4.5,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Beachfront Suite'],
        amenities: ['Free WiFi', 'Beach Access', 'Complimentary Drinks'],
        image: 'https://media.istockphoto.com/id/1333257950/photo/digitally-rendered-image-of-a-five-star-hotel-interior.jpg?s=612x612&w=0&k=20&c=cAMaQYc-dDz8xveLeM_-xsGtn41-2BJKRA6GrDuy-HE=',
    },
    {
        id: 8,
        name: 'Rustic Retreat Hotel',
        location: 'Napa Valley, CA',
        rating: 4.8,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Wine Country Suite'],
        amenities: ['Free WiFi', 'Wine Tasting', 'Outdoor Pool'],
        image: 'https://media.istockphoto.com/id/92007666/photo/posh-hotel-front.jpg?s=612x612&w=0&k=20&c=oJ_9x6kG-WO-8t_BIRWE3D4GN6pXLulmf7Lztr4Y-y8=',
    },
    {
        id: 9,
        name: 'Charming Cottage Hotel',
        location: 'Lake Tahoe, CA',
        rating: 4.6,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Family Suite'],
        amenities: ['Free WiFi', 'Lake Access', 'Fire Pit'],
        image: 'https://media.istockphoto.com/id/1418784247/photo/luxury-hotel-lobby.jpg?s=612x612&w=0&k=20&c=6acpCJL56bu5DMs8LwkdY246wlH2eRFci0MKVyycLJw=',
    },
    {
        id: 10,
        name: 'City Escape Hotel',
        location: 'Chicago, IL',
        rating: 4.3,
        price: getRandomPrice(),
        rooms: ['Single', 'Double', 'Penthouse'],
        amenities: ['Free WiFi', 'City View', 'Restaurant'],
        image: 'https://media.istockphoto.com/id/1333257950/photo/digitally-rendered-image-of-a-five-star-hotel-interior.jpg?s=612x612&w=0&k=20&c=cAMaQYc-dDz8xveLeM_-xsGtn41-2BJKRA6GrDuy-HE=',
    },
];

